# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\WebUser:
            algorithm: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [user_db_provider, qrcode_user_db_provider, api_key_user_provider]
        user_db_provider:
            entity:
                class: AppBundle:WebUser
                property: username
        qrcode_user_db_provider:
            entity:
                class: AppBundle:WebUser
                property: phone
        api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: user_db_provider
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login: 
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            context: myapp
        qrcode:
            pattern: ^/api
            stateless: false
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
            context: myapp
            
    access_control:
        - { path: ^/secret, roles: ROLE_USER }
        #- { path: ^/api, roles: ROLE_USER }
