# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    apikey_authenticator:
        class:     AppBundle\Security\ApiKeyAuthenticator
        public:    false
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine.orm.entity_manager"]
    app.qrcode_routines:
        class:     AppBundle\Service\QrCodeRoutinesService
        arguments: ["@doctrine.orm.entity_manager"]
